mixed-port: 7890
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query

proxies:
  - name: "Drodo-TrojanWS"
    type: trojan
    server: 104.18.24.139
    port: 443
    password: 6e1be706-da03-4643-9cff-37dbfb8833ec
    udp: true
    sni: id1.servercepat.net
    alpn: 
      - h2
      - http/1.1
    network: ws
    tls: true
    skip-cert-verify: false
    ws-opts:
      path: "/trojan-ws"
      headers:
        Host: id1.servercepat.net

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - Drodo-TrojanWS
      - DIRECT

  - name: DIRECT
    type: direct

rules:
  - GEOIP,ID,DIRECT
  - MATCH,PROXY
